### ISSUE TITLE
(Solved) Failed to build example

### ISSUE THREAD

**Issue by winston-wen** [apache/incubator-teaclave-trustzone-sdk#100]
Running `<repo>/Makefile` fails at  `aarch64-none-linux-gnu/bin/ld: cannot find -lteec` .
I've added the directory which contains `libteec.*` to `LIBRARY_PATH` and `LD_LIBRARY_PATH`.

**Comment by winston-wen** [comment]
今天在一个全新的阿里云节点上重新运行 [这个教程](https://teaclave.apache.org/blog/2021-10-14-developing-teaclave-application-with-teaclave-trustzone-sdk/#%E5%87%86%E5%A4%87%E6%9D%A1%E4%BB%B6) ，能正常编译。

昨天遵循 [这个教程](https://teaclave.apache.org/blog/2021-10-14-developing-teaclave-application-with-teaclave-trustzone-sdk/#%E5%87%86%E5%A4%87%E6%9D%A1%E4%BB%B6)，在`make example`的时候遇到了`cannot find -lteec`的错误，分别进入每个example去make，也遇到相同的错误。小改一下Makefile，给cargo加了`-vv`选项，发现cargo在调gcc的时候传了两个libteec链接参数，分别是 `-L <repo>/optee/optee_client/out/libteec` 和 `-lteec`。

我苦思冥想，找不到`-lteec`是从哪传的，所以提了这个issue。现在看来，很可能是我编译其他项目时污染了全局配置。

**Comment by DemesneGH** [comment]
@winston-wen 好的，我先暂时close这个issue，如有问题可以reopen，谢谢！
