### ISSUE TITLE
(Solved) Failed to build repo with optee-3.18.0

### ISSUE THREAD

**Issue by winston-wen** [apache/incubator-teaclave-trustzone-sdk#101]
I was following [this blogpost](https://teaclave.apache.org/blog/2021-10-14-developing-teaclave-application-with-teaclave-trustzone-sdk/), but replaced optee with higher version. When executing this command, 
```
make QEMU_VIRTFS_ENABLE=y CFG_TEE_RAM_VA_SIZE=0x00300000
```
I encountered the following error message:
```
make[1]: Entering directory '/home/user/optee-qemuv8-3.18.0/qemu'
changing dir to build for make ""...
make[2]: Entering directory '/home/user/optee-qemuv8-3.18.0/qemu/build'
config-host.mak is out-of-date, running configure
bash: line 3: ./config.status: No such file or directory
make[2]: *** No rule to make target 'config-host.mak', needed by 'meson.stamp'.  Stop.
make[2]: Leaving directory '/home/user/optee-qemuv8-3.18.0/qemu/build'
make[1]: *** [GNUmakefile:11: all] Error 2
make[1]: Leaving directory '/home/user/optee-qemuv8-3.18.0/qemu'
make: *** [Makefile:236: qemu] Error 2
```

optee-3.14.0, which is mentioned in the blogpost, is OK.

**Comment by DemesneGH** [comment]
Hi @winston-wen 
Teaclave TrustZone SDK has been tested with OP-TEE 3.18.0.
It seems you have issues with building OP-TEE 3.18.0 Repo (not the SDK), maybe previous building outputs remained in the directory. Suggest cleaning your `optee-qemuv8-3.18.0` directory, executing `repo sync` and trying again.

**Comment by winston-wen** [comment]
A fresh build solved this issue! Thanks for your patience!

**Comment by DemesneGH** [comment]
@winston-wen Happy to help.
