### ISSUE TITLE
API doc links broken

### ISSUE THREAD

**Issue by tchebb** [apache/incubator-teaclave-trustzone-sdk#106]
The following links:
- https://teaclave.apache.org/api-docs/trustzone-sdk/optee-teec/
- https://teaclave.apache.org/api-docs/trustzone-sdk/optee-utee/

referenced by both the "Docs" dropdown on the [main Teaclave site](https://teaclave.apache.org/) and by [this project's README](https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/4031e7282a8f398f54faa19acb2b84fab05de877/README.md?plain=1#L224-L227) go to a 404 page. The Internet Archive's last record of them working was on March 21st.

**Comment by DemesneGH** [comment]
@mssun Could you provide some guidance for me to fix this? I noticed the docs of other projects are also broken, such as `https://teaclave.apache.org/api-docs/client-sdk-rust/`. Thanks!

**Comment by henrysun007** [comment]
I have uploaded the documents to the website in https://github.com/apache/incubator-teaclave-website just now. Please check the links out.

**Comment by DemesneGH** [comment]
@henrysun007 Great. Thanks!
