### ISSUE TITLE
Make Panic Handler Optional

### ISSUE THREAD

**Issue by ivila** [apache/incubator-teaclave-trustzone-sdk#145]
In no-std branch, teaclave SDK define a panic handler, which stop ta developer from setting an custom one (for example, we would like to log the panic information before calling TEE_Panic).
https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/3177d4fa06f77afb351d0a19b8aa51b4a50fa1c8/optee-utee/src/lib.rs#L36

I think we should add a feature flag to let developer choose if they really need to disable the default one, just like this issue: [rust-osdev/uefi-rs: Make panic handler optional](https://github.com/rust-osdev/uefi-rs/issues/177)

**Comment by b49020** [comment]
Looks reasonable to me, feel free to create corresponding PR.

**Comment by ivila** [comment]
@b49020 Thanks for your patience, a PR has already created.

**Comment by ivila** [comment]
Done
