### ISSUE TITLE
Add license headers to source files and check in PR process

### ISSUE THREAD

**Issue by kezhenxu94** [apache/incubator-teaclave-trustzone-sdk#28]
Hi the community, I saw there are lots of files missing Apache License headers, it's kind of painful to recognize and add missing headers to those files, we created [license-eye](http://github.com/apache/skywalking-eyes) to help add missing license header for existing files.

License-eye is also able to be run as GitHub Actions, which make it possible to check and verify the license header during PR process, preventing future new files missing headers too. 

If you're interested in this tool, I'm glad to help to set it up in this repo, and add headers to existing files.

Thanks

**Comment by mssun** [comment]
Hi @kezhenxu94, this is very helpful. Sure, I'm very interested in this tool.
