### ISSUE TITLE
关于ta程序使用第三方库

### ISSUE THREAD

**Issue by gaojunjie03** [apache/incubator-teaclave-trustzone-sdk#56]
您们好！我之前也有调研过你们基于intel sgx的teaclave项目，发现里面的rust可信区域代码和python可信区域代码（mesapy）是不能使用第三方库的，就算要使用，也要使用rust-sgx-sdk进行修改调整之后才能用。 那这次的这个trustzone-sdk的ta程序能否直接使用第三方库？比如crates.io里面的

**Comment by DemesneGH** [comment]
@gaojunjie03 

> trustzone-sdk的ta程序能否直接使用第三方库

可以。参考：https://github.com/apache/incubator-teaclave-trustzone-sdk/tree/master/examples/serde-rs

**Comment by gaojunjie03** [comment]
> @gaojunjie03
> 
> > trustzone-sdk的ta程序能否直接使用第三方库
> 
> 可以。参考：https://github.com/apache/incubator-teaclave-trustzone-sdk/tree/master/examples/serde-rs

谢谢，那如果是调用第三方动态链接库呢？比如用go、python等语言编写的so库，ta可以链接使用吗？

**Comment by DemesneGH** [comment]
@gaojunjie03 

> 调用第三方动态链接库呢？

可以。这个是TA链接静态库的代码：https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/c47db9923ebb1cce374e3a42dac21a6424bb897c/examples/hello_world-rs/ta/build.rs#L60

动态库改成`rustc-link-lib=dylib=[library name]`。

**Comment by gaojunjie03** [comment]
> @gaojunjie03
> 
> > 调用第三方动态链接库呢？
> 
> 可以。这个是TA链接静态库的代码：
> 
> https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/c47db9923ebb1cce374e3a42dac21a6424bb897c/examples/hello_world-rs/ta/build.rs#L60
> 
> 动态库改成`rustc-link-lib=dylib=[library name]`。

收到 谢谢！！
