### ISSUE TITLE
Emulator example unclear

### ISSUE THREAD

**Issue by abhath-labs** [apache/incubator-teaclave-trustzone-sdk#61]
Hi, I've been trying to run the example program as described [here](https://teaclave.apache.org/trustzone-sdk-docs/getting-started-with-optee-for-qemu-armv8/) but I am confused on what to be done in this step
`mkdir shared && mount -t 9p -o trans=virtio host shared`

Running it inside the qemu emulator results in error : Unrecognised command
Running it outside results in error : No Permission

Could you pls suggest what I might be doing wrong. Thanks

**Comment by DemesneGH** [comment]
Hi @abhath-labs 


> mkdir shared && mount -t 9p -o trans=virtio host shared

should be executed inside the QEMU guest terminal (which is listening on the 54320 port).

**Comment by abhath-labs** [comment]
<img width="424" alt="Screenshot 2022-03-08 at 11 05 44 AM" src="https://user-images.githubusercontent.com/99468748/157184672-3df72a56-f900-4975-8a78-e784eb71d357.png">

Thanks for the quick response, I tried that and get this error, to clarify I'm running this inside the docker container so I'm following the steps for the non GUI version

**Comment by DemesneGH** [comment]
Hi @abhath-labs 
It seems like the QEMU monitor terminal, not the guest terminal.
Enter "c" in QEMU monitor terminal to boot up.
Then you will see the guest terminal spawned by:
```
$ nc -l 127.0.0.1 -p 54320
```

**Comment by stanly-johnson** [comment]
I see, thanks, but it looks like the boot up is failing for me, this is the output that I'm seeing

QEMU monitor
<img width="573" alt="Screenshot 2022-03-08 at 11 49 14 AM" src="https://user-images.githubusercontent.com/6850913/157191045-e7533bd9-27a1-4022-a615-0ab9dde1534a.png">

`nc -l 127.0.0.1 -p 54320`
<img width="662" alt="Screenshot 2022-03-08 at 11 49 28 AM" src="https://user-images.githubusercontent.com/6850913/157191127-ed8080f4-3a0e-4a14-a114-095c556fea70.png">


`nc -l 127.0.0.1 -p 54321`
<img width="1030" alt="Screenshot 2022-03-08 at 11 49 39 AM" src="https://user-images.githubusercontent.com/6850913/157191194-e02f1d5a-f279-4206-85f8-07159abbdc5d.png">

**Comment by abhath-labs** [comment]
I see, thanks, but the emulator boot up fails for me, this is the output I'm seeing

QEMU monitor
<img width="573" alt="Screenshot 2022-03-08 at 11 49 14 AM" src="https://user-images.githubusercontent.com/99468748/157191431-e7511a91-9647-4ffe-aa26-7c6804fe7843.png">

`nc -l 127.0.0.1 -p 54320`
<img width="662" alt="Screenshot 2022-03-08 at 11 49 28 AM" src="https://user-images.githubusercontent.com/99468748/157191482-8a1158b5-f102-4c52-b76b-1f5ffe232eab.png">

`nc -l 127.0.0.1 -p 54321`
<img width="1030" alt="Screenshot 2022-03-08 at 11 49 39 AM" src="https://user-images.githubusercontent.com/99468748/157191527-d16db7bc-d874-46b6-9531-4682195eec00.png">

**Comment by DemesneGH** [comment]
@abhath-labs 
Try to rebuild the Linux kernel image?
Nothing wrong with QEMU and OP-TEE OS.

**Comment by abhath-labs** [comment]
Hi @DemesneGH 
Thankyou, rebuilding the kernel with the default options fixed the error, I chose some non-default settings which led to the kernel error. No when I try to run the command `mount -t 9p -o trans=virtio host shared`
I get the error,  `mount: /home/incubator-teaclave-trustzone-sdk/optee-qemuv8-3.14.0/build/shared: permission denied.`

The output in the QEMU terminal after starting it with `make run-only` is as follows
```
* QEMU is now waiting to start the execution
* Start execution with either a 'c' followed by <enter> in the QEMU console or
* attach a debugger and continue from there.
*
* To run OP-TEE tests, use the xtest command in the 'Normal World' terminal
* Enter 'xtest -h' for help.

c

```

The same user (sudo) is used to start the QEMU and mount, not sure why the permission denied error is occuring.

**Comment by DemesneGH** [comment]
Hi @abhath-labs 


> I get the error, `mount: /home/incubator-teaclave-trustzone-sdk/optee-qemuv8-3.14.0/build/shared: permission denied.`

Is that error message printed from the  QEMU guest terminal (port 54320)?


The `mount` command should be executed inside QEMU guest, and


> /home/incubator-teaclave-trustzone-sdk/optee-qemuv8-3.14.0/build/shared

that path should not exist in the QEMU guest.

**Comment by abhath-labs** [comment]
> Is that error message printed from the QEMU guest terminal (port 54320)?

Yes, also when I run `make-only` and then `c` in terminal, the QEMU guest terminal exits, is this normal?

> that path should not exist in the QEMU guest.

Not sure I understand, this directory is created just before this command right? 
`mkdir shared && mount -t 9p -o trans=virtio host shared`, are you saying it should not exist before mkdir, then you're right, it does not exist

**Comment by DemesneGH** [comment]
hi @abhath-labs 

> /home/incubator-teaclave-trustzone-sdk/optee-qemuv8-3.14.0/build/

I mean that path is probably the host path (not the guest path). I'm not sure whether the `mount` command was executed **inside the guest**.

Can you paste all the guest terminal's output here?
