### ISSUE TITLE
Get Public/Private key from generated key in TA

### ISSUE THREAD

**Issue by syedelec** [apache/incubator-teaclave-trustzone-sdk#85]
Hi

In op-tee it's possible to use TEE API functions such as `TEE_GetObjectBufferAttribute` to fetch some attributes regarding the generated key however I could not find the function in the rust sdk.

Could you point me to an equivalent solution?

Thanks

**Comment by DemesneGH** [comment]
Same as `TEE_GetObjectBufferAttribute`, you can invoke this method: https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/972760f5bd9777104e653fc31a32da096f1955bd/optee-utee/src/object.rs#L242-L250

**Comment by syedelec** [comment]
Thanks! I missed that.
