### ISSUE TITLE
Xargo Version?

### ISSUE THREAD

**Issue by Rand0x** [apache/incubator-teaclave-trustzone-sdk#87]
I tried to build it with Xargo 0.3.26 and it failed.
I tried it with Xargo 0.3.22 and it works?

With Xargo 0.3.26 it says that aarch64-unknown-optee-trustzone may be not installed

**Comment by DemesneGH** [comment]
Hi @Rand0x 

> I tried to build it with Xargo 0.3.26 and it failed.

Try to clean your building environment and rebuild? 
After executing `setup.sh`, the Xargo will be installed as `0.3.26` and the building process works fine. Other versions of Xargo have not been tested.
