### ISSUE TITLE
./hello_world-rs not found in shared folder

### ISSUE THREAD

**Issue by HakonToemte** [apache/incubator-teaclave-trustzone-sdk#94]
Hello, I wish to develop a new CA/TA in OPTEE using Rust with QEMUv8. I have been following this [guide](https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/master/README.md), and created a shared folder to run these applications in QEMU. I am now trying to see if i can alter hello_world-rs to use a different number than the original example does. But even though it seems that i have succesfully shared the installed examples,  I get error: not found.
![Issue](https://user-images.githubusercontent.com/55509202/191357278-7f8db593-b575-403f-8e5c-01797bcfde87.png)

I found this [issue](https://github.com/apache/incubator-teaclave-trustzone-sdk/issues/67), and I can run hello_world-rs, but that's the original and unaltered example. I want to run my new, altered version. 
![image](https://user-images.githubusercontent.com/55509202/191358267-b873b283-622f-406f-b9dd-5c24ed18456e.png)
The file should be executable.
![image](https://user-images.githubusercontent.com/55509202/191360991-bc538270-1ff6-4e63-9004-e39a87a65660.png)

I am very thankful for any help with this!

**Comment by DemesneGH** [comment]
Hi @HakonToemte ,
Seems this error occurs in some cases, but I've not reproduced it. Let's check these items to figure it out:
- What's your building environment? We recommend using our docker `teaclave/teaclave-trustzone-sdk-build:0.3.0`. I'm not sure if the building environment causes this error.
- Check the file type in your building environment: `file ./hello_world-rs`
- Check the dependency libraries in QEMU: `# ldd ./hello_world-rs`

Thanks!

**Comment by HakonToemte** [comment]
Thanks for the quick response! My building environment is built by first following [OP-TEE with Rust](https://optee.readthedocs.io/en/latest/building/optee_with_rust.html), then [Build & Install](https://github.com/apache/incubator-teaclave-trustzone-sdk#build--install), then Run Rust applications. I have not used docker. I hope that answers the first question.

file ./hello_world-rs
![image](https://user-images.githubusercontent.com/55509202/191466497-b30e840f-8425-4a54-9965-83396c547d4d.png)

ldd ./hello_world-rs
![image](https://user-images.githubusercontent.com/55509202/191466250-7106457e-d543-4924-8c23-7f80fe6baf27.png)

**Comment by DemesneGH** [comment]
@HakonToemte It seems the `hello_world-rs` you built is a 32-bit (arm) ELF which is not compatible with the 64-bit (aarch64) QEMUv8 platform. Suggest to unset `ARCH`  and rebuild the host app, reference: https://github.com/apache/incubator-teaclave-trustzone-sdk#build--install.

**Comment by DemesneGH** [comment]
> then compile the example again and update the shared_folder

Yes, you just need to recompile the example you've modified:

```
$ make -C examples/your-example
```

Then copy the CA and TA into shared_folder:
```
$ cp example/your-example/host/target/aarch64-unknown-linux-gnu/release/[your CA] path/to/shared/folder
$ cp example/your-example/ta/target/aarch64-unknown-optee-trustzone/release/[your TA] path/to/shared/folder
```
After copying ta into `/lib/optee_armtz` you can run the new CA you built.


> If I want to create a new CA/TA, is there a good guide for that?

There is no documentation about writing a new CA/TA now. You can follow these steps to write your Rust example:
1. Duplicate the `hello_world-rs` example and modify the code upon it.
2. Decide commands the host app sends to TA, and modify `proto/src/lib.rs`
3. In host:
     - modify the app name in `host/Makefile` and `host/Cargo.toml`
     - write your logic in host/src/main.rs
4. In TA:
     - generate a random `uuid` and modify `uuid.txt`
     - write your logic in ta/src/main.rs
5. build your example

**Comment by HakonToemte** [comment]
That was been tremendous help, thank you very much!
