### ISSUE TITLE
make optee: fatal error: uuid/uuid.h: No such file or directory

### ISSUE THREAD

**Issue by HakonToemte** [apache/incubator-teaclave-trustzone-sdk#96]
Hey, I have been successful in building on my laptop, but now when i try to build on my personal computer i run into this issue. When running make optee.

![image](https://user-images.githubusercontent.com/55509202/193769910-ed34cb5e-5835-4b1d-a0fd-3b1eead853f4.png)

The problem is commonly related to not having the uuid-dev package it seems, but I have installed all [prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html).
![image](https://user-images.githubusercontent.com/55509202/193771873-40181a17-b49e-49a6-ad9e-4cdd43e1c1ea.png)

Thankful for any help!

**Comment by HakonToemte** [comment]
The teeacl.h file seems to run fine if i compile it manually.
![image](https://user-images.githubusercontent.com/55509202/194048057-1809ff42-d8d1-46a5-aec4-3d6a4d924db6.png)

So i'm guessing maybe a path is being set wrong?
I have first followed [Optee with Rust](https://optee.readthedocs.io/en/latest/building/optee_with_rust.html)
Then export OPTEE_DIR=~/Bachelor/YOUR_OPTEE_DIR3
./setup.sh
source environment
make optee
then make optee returns the error

Any idea what could be wrong?

**Comment by DemesneGH** [comment]
Hi @HakonToemte 
It seems that the `libteeacl` was added into `optee_client` 6 days ago, and some dependency was not satisfied in the current building environment of Teaclave TrustZone SDK.
As a temporary workaround, you can checkout the latest release version of OP-TEE (3.18.0):
```
$ cd YOUR_OPTEE_DIR
$ repo init -m qemu_v8.xml -b 3.18.0
$ repo sync
```
Then try to build again.

**Comment by HakonToemte** [comment]
Thanks for the reply :)
That explains it, because it felt like a new error.
I followed your steps above, then tried to make optee again.
which now gave this error.
![image](https://user-images.githubusercontent.com/55509202/194102468-90679377-d3f0-4b68-addc-614800ddbd9d.png)

**Comment by HakonToemte** [comment]
It worked now! :)
For some reason, doing `repo init -m qemu_v8.xml -b 3.18.0`
on my existing project ended up resulting in the error above. But making a whole new folder with
`repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.18.0` works perfectly.

Either way, thanks again @DemesneGH !

**Comment by DemesneGH** [comment]
> For some reason, doing `repo init -m qemu_v8.xml -b 3.18.0`
> on my existing project ended up resulting in the error above.

Seems the previous building outputs should be cleaned. Running `make clean` before `make optee` will probably solve this error.

**Comment by mssun** [comment]
The issue has been resolved. Closed.
